<?php

namespace App\Services;

use App\Models\Company;
use Illuminate\Support\Str;

/**
 * Handles the enrollment of iPhone/iPad devices via the
 * Apple MDM protocol.
 *
 * Unlike Android (where Google acts as the MDM server for us via the
 * Android Management API), here WE are the MDM server: we have to sign
 * the configuration profile, expose the check-in endpoints and
 * send APNs pushes to wake up the devices.
 *
 * CURRENT STATE: a stub that only works for the "generate QR" flow,
 * but generating the actual signed profile requires two prerequisites
 * that are still missing (see Company::hasApnsConfigured()):
 *
 *   1. An "MDM Vendor" certificate (CSR signed by Apple, required
 *      as an Apple Developer Enterprise with the account flagged for MDM use).
 *   2. An APNs push certificate, generated by signing a CSR with the
 *      vendor certificate and uploading it to https://identity.apple.com/pushcert/
 *
 * TODO once the certificates are available:
 *   - implement buildMobileconfig() to generate the enrollment plist
 *     (PayloadType: Profile Service or directly the MDM payload)
 *   - sign it in CMS/PKCS#7 with the vendor certificate (openssl smime -sign)
 *   - implement the /mdm/checkin endpoints (Authenticate, TokenUpdate,
 *     CheckOut) and /mdm/command (command queue) — see the Apple MDM Protocol
 *     Reference: https://developer.apple.com/documentation/devicemanagement
 *   - implement sending the "wake up" push via ApnsService
 */
class IosMdmService
{
    /**
     * Creates a local iOS enrollment "token" (there's no Google
     * equivalent to call here: the token is ours, generated and kept
     * only in our own database).
     *
     * Returns the public URL of the enrollment profile to encapsulate
     * in the QR code. This is the URL that the iPhone/iPad opens in Safari
     * after scanning, to download and install the .mobileconfig profile.
     */
    public function createEnrollmentToken(Company $company): array
    {
        if (! $company->hasApnsConfigured()) {
            throw new \RuntimeException(
                'Unable to generate an iOS enrollment: this company is missing the APNs push certificate.'
            );
        }

        $localToken = (string) Str::uuid();

        // The URL that will go into the QR code. The controller responding to
        // this route (to be implemented) must return the signed .mobileconfig
        // with Content-Type: application/x-apple-aspen-config.
        $profileUrl = route('ios-mdm.profile', ['token' => $localToken]);

        return [
            'local_token' => $localToken,
            'qr_payload' => $profileUrl,
            // Apple enrollment profiles don't have their own expiration
            // like Android tokens do; here we apply an "our own"
            // application-side expiration, past which the link stops working.
            'expires_at' => now()->addHour(),
        ];
    }

    /**
     * TODO: to be implemented once the vendor cert and push
     * certificate are available. Must generate the MDM enrollment
     * profile plist and return it signed in CMS (PKCS#7 detached or attached).
     */
    public function buildSignedMobileconfig(Company $company, string $localToken): string
    {
        throw new \RuntimeException(
            'buildSignedMobileconfig() not yet implemented: the MDM vendor certificate and the APNs push certificate are needed first.'
        );
    }
}
